site_name: Sinesp
site_author: Grupo 5
site_description: >-
  Documentação para o projeto de avaliação da disciplina de requisitos de software 
 
# Repository
repo_url: https://github.com/Requisitos-de-Software/2024.1-Sinesp_Cidadao
repo_name: 2024.1-Sinesp_Cidadao


# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  favicon: assets/logo.png
  logo: ../assets/Logos/Logo_sinesp.png
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
     
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

  extra_css: [stylesheets/extra.css]
  
nav: 
  - Início: index.md
  - Atas:
      - Ata 1: atas/Ata_Reuniao1_25_03_2024.md
      - Ata 2: atas/Ata_Reuniao2_31_03_2024.md
      - Ata 3: atas/Ata_Reuniao3__07_04_2024.md
      - Ata 4: atas/Ata_Reuniao4_14_04_2024.md
      - Ata 5: atas/Ata_Reuniao5_19_04_2024.md
      - Ata 6: atas/Ata_Reuniao6_13_05_2024.md
      - Ata 7: atas/Ata_Reuniao7_18_05_2024.md
      - Ata 8: atas/Ata_Reuniao8_20_05_2024.md
  - Apresentações: 
      - Apresentação 1: Apresentacoes/apresentacao_1.md
      - Apresentação 2: Apresentacoes/apresentacao_2.md
      - Apresentação 3: Apresentacoes/apresentacao_3.md
      - Apresentação 4: Apresentacoes/apresentacao_4.md
  - Planejamento:
      - Lista de Aplicativos: Planejamento/Lista_de_aplicativos.md
      - Aplicativo Escolhido: Planejamento/App_selecionado.md
      - Cronograma Planejado: Planejamento/cronograma.md
      - Cronograma executado: Planejamento/Cronograma_Executados.md
      - Heatmap: Planejamento/heatmap.md
      - Rich Pictures: Planejamento/Rich_pictures.md
      - Ferramentas: Planejamento/ferramentas.md
  - Elicitação: 
      - Perfil de usuário: elicitacao/Perfil_de_usuario.md
      - Personas: elicitacao/personas.md
      - Técnicas:
          - Questionario: elicitacao/tecnicas/questionario.md
          - Analise de Interface: elicitacao/tecnicas/AnaliseDaInterface.md
          - Analise de Documento: elicitacao/tecnicas/AnaliseDeDocumento.md
          - Analise de Protocolo: elicitacao/tecnicas/AnaliseDeProtocolo.md
          - Entrevista: elicitacao/tecnicas/Entrevista.md
          - Introspecção: elicitacao/tecnicas/Introspeccao.md
          - Storytelling: elicitacao/tecnicas/storytelling.md
      - Requisitos Elicitados: elicitacao/tecnicas/Requisitos_elicitados.md
      - Priorização: 
          - MOSCOW: elicitacao/priorizacao/Moscow.md
          - 100$: elicitacao/priorizacao/100$.md
          - FTF: elicitacao/priorizacao/FTF.md
          - Three Scales: elicitacao/priorizacao/three_scales.md
  - Modelagem:
      - Casos de uso: Modelagem/Casos_De_uso.md
      - Léxicos: Modelagem/Lexico.md
      - Especificação Suplementar: Modelagem/especificacao_suplementar.md
      - Cenários: Modelagem/Cenarios.md
      - Ágil:
          - Histórias de Usuário: Modelagem/Agil/Historias_de_Usuario.md
          - Backlog: Modelagem/Agil/backlog.md
          - NFR Framework: Modelagem/Agil/NFR.md
  - Verificação - Grupo 6:
          - Entrega 3:
            - Planejamento: Verificacao/entrega3/planejamento_entr_3.md
            - Casos de uso: Verificacao/entrega3/verifica_casosdeuso.md
            - Léxicos: Verificacao/entrega3/verifica_lexicos.md
            - Especificação Suplementar: Verificacao/entrega3/verifica_Especificacao.md
            - Cenários: Verificacao/entrega3/verifica_cenarios.md
          - Entrega 4: 
            - Planejamento : Verificacao/entrega4/planejamento_entr_4.md
            - Histórias de Usuário: Verificacao/entrega4/verifica_user.md
            - Backlog: Verificacao/entrega4/verifica_backlog.md
            - NFR Framework: Verificacao/entrega4/verifica_nfr.md
      


